##??????
##spring.super.scheduled.plug-in.executionFlag=true
###????????????????????????
spring.super.scheduled.plug-in.executionLog=true
###??????????????????????
##spring.super.scheduled.plug-in.logPath=E:/tmp/log-scheduled
#
#spring.super.scheduled.plug-interfaces.executionFlag=true
#spring.super.scheduled.plug-interfaces.executionLog=true
#spring.super.scheduled.plug-interfaces.logPath=E:/tmp/log-scheduled
#smail.address = xxx@chinamobile.com
#mail.receiver = xxx@126.com
#????
spring.mail.host=smtp.qq.com
spring.mail.username=541970950@qq.com
spring.mail.password=sgcgymzqzgjrbbee
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
#JPA
spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.jackson.serialization.indent_output=false