##??????
##spring.super.scheduled.plug-in.executionFlag=true
###????????????????????????
spring.super.scheduled.plug-in.executionLog=true
###??????????????????????
##spring.super.scheduled.plug-in.logPath=E:/tmp/log-scheduled
#
#spring.super.scheduled.plug-interfaces.executionFlag=true
#spring.super.scheduled.plug-interfaces.executionLog=true
#spring.super.scheduled.plug-interfaces.logPath=E:/tmp/log-scheduled
